import Link from "next/link";
import { BarChart3, ChevronRight, CircleDollarSign, FileText } from "lucide-react";
import { CustomerPortalSection } from "@/components/customer-portal-section";
import { CustomerRequestModal } from "@/components/customer-request-modal";
import { getCustomerSession } from "@/lib/customer-auth";
import { createSupabaseServerClient } from "@/lib/supabase-server";
import { redirect } from "next/navigation";

export const dynamic = "force-dynamic";
export default async function CustomerInvestmentsPage() {
  const { customer } = await getCustomerSession(); if (!customer) redirect("/auth/login?redirectTo=/portal/investments");
  const { data: investments = [] } = await createSupabaseServerClient().from("investments").select("id, uuid, amount, vehicle, status, submitted_at, created_at, start_date, end_date, payout_schedule").eq("customer_id", customer.id).order("created_at", { ascending: false });
  const active = investments.filter((item) => item.status === "active").length;
  const value = investments.reduce((total, item) => total + Number(item.amount || 0), 0);
  return <CustomerPortalSection customer={customer} eyebrow="Portfolio" title="Your investments" description="Review every NEAT placement and open an investment to see its full details, schedule, and transaction history." action={<CustomerRequestModal type="investment" triggerLabel="Place an investment" triggerClassName="inline-flex items-center gap-2 rounded-xl bg-[#075ca8] px-4 py-3 text-sm font-black text-white shadow-[0_10px_22px_rgb(7_92_168_/_0.2)]" />}><section className="grid gap-4 sm:grid-cols-3"><Metric icon={BarChart3} label="Total requested" value={`₦${value.toLocaleString()}`} /><Metric icon={CircleDollarSign} label="Active placements" value={active.toString()} /><Metric icon={FileText} label="All requests" value={investments.length.toString()} /></section><section className="mt-7 overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-100 px-6 py-5"><h2 className="text-lg font-black text-slate-950">Investment register</h2><p className="mt-1 text-sm font-semibold text-slate-500">Select any investment to view its full account record.</p></div>{investments.length ? <div className="divide-y divide-slate-100">{investments.map((item) => <Link key={item.id} href={`/portal/investments/${item.uuid || item.id}`} className="flex flex-wrap items-center justify-between gap-4 px-6 py-5 transition hover:bg-slate-50"><div className="flex items-center gap-4"><span className={`grid size-11 place-items-center rounded-2xl ${item.vehicle === "funding" ? "bg-violet-50 text-violet-700" : "bg-blue-50 text-[#075ca8]"}`}><CircleDollarSign className="size-5" /></span><div><p className="font-black text-slate-950">{item.vehicle === "funding" ? "Ethical Funding" : "Ethical Investment"}</p><p className="mt-1 text-sm font-semibold text-slate-500">Created {new Date(item.created_at).toLocaleDateString("en-NG")} · {item.payout_schedule || "Payout schedule pending"}</p></div></div><div className="flex items-center gap-4"><div className="text-right"><p className="font-black text-slate-950">₦{Number(item.amount || 0).toLocaleString()}</p><span className="mt-1 inline-block rounded-full bg-slate-100 px-3 py-1 text-xs font-black capitalize text-slate-600">{item.status || "pending"}</span></div><ChevronRight className="size-5 text-slate-300" /></div></Link>)}</div> : <EmptyInvestment accountNumber={customer.account_number} />}</section></CustomerPortalSection>;
}

function Metric({ icon: Icon, label, value }) { return <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><Icon className="size-5 text-[#075ca8]" /><p className="mt-4 text-2xl font-black text-slate-950">{value}</p><p className="mt-1 text-xs font-bold text-slate-500">{label}</p></div>; }
function EmptyInvestment({ accountNumber }) { return <div className="px-6 py-14 text-center"><CircleDollarSign className="mx-auto size-10 text-slate-200" /><h3 className="mt-4 text-lg font-black">Your portfolio will appear here</h3><p className="mx-auto mt-2 max-w-md text-sm font-semibold leading-6 text-slate-500">Place your first investment request and use account {accountNumber || "details supplied by NEAT"} when the team confirms funding.</p></div>; }
