import Image from "next/image";
import Link from "next/link";
import { Check, LockKeyhole } from "lucide-react";
import { CustomerAuthForm } from "@/components/customer-auth-form";

function Brand() {
  return <Link href="/" className="inline-flex items-center gap-3" aria-label="NEAT Ethical home"><Image loading="lazy" src="/img/ethical-logo-nobg.png" alt="NEAT Ethical logo" width={52} height={52} className="size-12 object-contain"/><span className="text-[#002b58]"><strong className="block text-lg tracking-tight">NEAT</strong><small className="block text-[.62rem] font-bold uppercase tracking-[.16em] text-[#276da4]">Ethical investments</small></span></Link>;
}

export default function CustomerSignupPage() {
  return <main className="min-h-screen bg-[#f8fbff] lg:grid lg:grid-cols-[.92fr_1.08fr]"><section className="flex min-h-screen flex-col px-8 py-7"><Brand/><div className="mx-auto flex w-full flex-1 items-center justify-center py-10"><div className="w-full max-w-xl rounded-[2rem] border border-[#dce8f5] bg-white p-7 shadow-[0_24px_80px_rgba(0,43,88,.13)] sm:p-10"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.19em] text-[#276da4]">Create your account</p><h1 className="mt-3 font-sans text-3xl font-semibold tracking-tight text-[#002b58]">Start investing with purpose</h1></div><span className="grid size-12 shrink-0 place-items-center rounded-2xl bg-[#e8f2fb] text-[#0057a6]"><LockKeyhole className="size-5"/></span></div><p className="mt-4 mb-7 leading-6 text-[#52779c]">Set up your personal portal to request investments, funding, and loans — and track every response.</p><div className="[&_label]:text-[#002b58] [&_input]:border-[#ccdded] [&_input]:bg-[#fbfdff] [&_input]:outline-none [&_input:focus]:border-[#0057a6] [&_input:focus]:ring-4 [&_input:focus]:ring-[#dceefa] [&_button]:rounded-xl [&_button]:bg-[#0057a6] [&_button]:py-3.5 [&_button:hover]:bg-[#002b58] [&_a]:text-[#0057a6]"><CustomerAuthForm mode="signup"/></div></div></div><small className="hidden text-[#7c96b2] sm:block">© {new Date().getFullYear()} NEAT Ethical Investments</small></section><section className="relative hidden min-h-screen overflow-hidden bg-[#002b58] lg:block"><Image src="/images/ethical-investing-sprout.png" alt="A young seedling growing beside coins in rich soil" fill priority sizes="55vw" className="object-cover"/><div className="absolute inset-0 bg-[linear-gradient(120deg,rgba(0,43,88,.6),rgba(0,87,166,.3),rgba(0,43,88,.08))]"/><div className="relative flex h-3/4 max-w-xl flex-col justify-between px-12 py-12 xl:px-20"><div className="ml-auto rounded-full border border-white/20 bg-white/10 px-4 py-2 text-xs font-semibold text-white"><LockKeyhole className="mr-2 inline size-3.5"/>Protected account setup</div><div className="pb-7 text-white"><span className="mb-7 grid size-12 place-items-center rounded-2xl border border-white/30 bg-white/15"><Image loading="lazy" src="/img/ethical-logo-nobg.png" alt="NEAT Ethical logo" width={40} height={40} className="size-9 object-contain"/></span><p className="max-w-md text-5xl font-semibold leading-[1.04] tracking-tighter">A clearer start for every investment.</p><p className="mt-6 max-w-sm leading-7 text-white/80">Open your portal and keep your investment journey, requests, and next steps in one place.</p><p className="mt-9 flex gap-5 border-t border-white/20 pt-6 text-sm"><span><Check className="mr-2 inline size-4 text-[#a9d5ff]"/>Transparent process</span><span><Check className="mr-2 inline size-4 text-[#a9d5ff]"/>Built for impact</span></p></div></div></section></main>;
}
