import { CalendarClock, CircleDollarSign, FileText } from "lucide-react";
import { redirect } from "next/navigation";
import { CustomerPortalSection } from "@/components/customer-portal-section";
import { CustomerRequestModal } from "@/components/customer-request-modal";
import { getCustomerSession } from "@/lib/customer-auth";
import { createSupabaseServerClient } from "@/lib/supabase-server";

export const dynamic = "force-dynamic";
export default async function CustomerLoansPage() {
  const { customer } = await getCustomerSession(); if (!customer) redirect("/auth/login?redirectTo=/portal/loans");
  const { data: requests = [] } = await createSupabaseServerClient().from("loan_requests").select("id, uuid, amount, purpose, term_months, status, response_due_at, created_at, response_note").eq("customer_id", customer.id).order("created_at", { ascending: false });
  const pending = requests.filter((item) => item.status === "pending").length;
  return <CustomerPortalSection customer={customer} eyebrow="Loans" title="Loan centre" description="Request a loan, review your previous applications, and see when the NEAT team is due to respond." action={<CustomerRequestModal type="loan" triggerLabel="Request a loan" triggerClassName="inline-flex items-center gap-2 rounded-xl bg-[#075ca8] px-4 py-3 text-sm font-black text-white shadow-[0_10px_22px_rgb(7_92_168_/_0.2)]" />}><section className="grid gap-4 sm:grid-cols-3"><Metric icon={CircleDollarSign} label="Applications" value={requests.length} /><Metric icon={CalendarClock} label="Awaiting response" value={pending} /><Metric icon={FileText} label="Response promise" value="48 hrs" /></section><section className="mt-7 overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-100 px-6 py-5"><h2 className="text-lg font-black text-slate-950">Loan applications</h2><p className="mt-1 text-sm font-semibold text-slate-500">Each request is reviewed independently by the NEAT team.</p></div>{requests.length ? <div className="divide-y divide-slate-100">{requests.map((item) => <article key={item.id} className="px-6 py-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex items-center gap-3"><span className="grid size-11 place-items-center rounded-2xl bg-violet-50 text-violet-700"><CircleDollarSign className="size-5" /></span><div><p className="font-black text-slate-950">₦{Number(item.amount || 0).toLocaleString()} for {item.term_months} months</p><p className="mt-1 text-sm font-semibold text-slate-500">{item.purpose}</p></div></div><p className="mt-4 text-xs font-bold text-slate-400">Requested {new Date(item.created_at).toLocaleDateString("en-NG")}</p></div><div className="text-right"><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-black capitalize text-slate-600">{item.status}</span><p className="mt-3 text-xs font-bold text-slate-500">{item.status === "pending" ? `Response due ${new Date(item.response_due_at).toLocaleString("en-NG")}` : item.response_note || "Decision recorded"}</p></div></div></article>)}</div> : <div className="px-6 py-14 text-center"><CircleDollarSign className="mx-auto size-10 text-slate-200" /><h3 className="mt-4 text-lg font-black">No loan applications yet</h3><p className="mx-auto mt-2 max-w-md text-sm font-semibold leading-6 text-slate-500">When you need financing, send a request here and the NEAT team will respond within 48 hours.</p></div>}</section></CustomerPortalSection>;
}
function Metric({ icon: Icon, label, value }) { return <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><Icon className="size-5 text-violet-700" /><p className="mt-4 text-2xl font-black text-slate-950">{value}</p><p className="mt-1 text-xs font-bold text-slate-500">{label}</p></div>; }
