import { Resend } from "resend";
import { adminNotificationEmail, emailTemplate, temporaryCredentialsEmail, welcomeEmail } from "@/lib/email-templates";
import { staffRecipients } from "@/lib/notification-config";

const from = process.env.RESEND_FROM || "NEAT Ethical Investments <info@neatethical.com>";
const siteUrl = (process.env.NEXT_PUBLIC_SITE_URL || "http://localhost:3000").replace(/\/$/, "");
const mailer = () => { if (!process.env.RESEND_API_KEY) throw new Error("RESEND_API_KEY is not configured."); return new Resend(process.env.RESEND_API_KEY); };
async function send({ to, subject, html, text }) { if (!to?.length) return null; const { data, error } = await mailer().emails.send({ from, to, subject, html, text }); if (error) throw new Error(error.message || "Email could not be sent."); return data; }
async function notifyAdmins(title, text, details = []) { return send({ to: staffRecipients(), subject: title, html: adminNotificationEmail({ title, text, details, portalUrl: `${siteUrl}/dashboard` }), text }); }

export async function sendPortalSignupEmail(customer) { const portalUrl = `${siteUrl}/portal`; return Promise.all([send({ to: [customer.email], subject: "Welcome to NEAT Ethical Investments", html: welcomeEmail(customer, portalUrl), text: `Welcome ${customer.first_name}. Your account number is ${customer.account_number}. Open your portal: ${portalUrl}` }), notifyAdmins(`New customer signup: ${customer.first_name} ${customer.last_name}`, "A customer created a self-service portal account.", [["Customer", `${customer.first_name} ${customer.last_name}`], ["Email", customer.email], ["Account", customer.account_number]])]); }
export async function sendPasswordChangeCodeEmail(customer, code) { const text = `Use this code to change your NEAT Ethical password: ${code}. It expires in 10 minutes.`; return send({ to: [customer.email], subject: "Your NEAT password change code", html: emailTemplate({ title: "Password change code", intro: "Enter this code in the customer portal to continue changing your password.", details: [["Confirmation code", code]], footer: "This code expires in 10 minutes. If you did not request this, you can safely ignore this email." }), text }); }
export async function sendPortalInvestmentEmails({ customer, investment, temporaryPassword = null }) {
  const loginUrl = `${siteUrl}/auth/login`;
  const customerMessages = temporaryPassword
    ? [
        send({ to: [customer.email], subject: "Welcome to NEAT Ethical Investments", html: welcomeEmail(customer, loginUrl), text: `Welcome ${customer.first_name}. Your account number is ${customer.account_number}. Sign in: ${loginUrl}` }),
        send({ to: [customer.email], subject: "Your NEAT login details", html: temporaryCredentialsEmail(customer, temporaryPassword, loginUrl), text: `Sign in with ${customer.email} and temporary password ${temporaryPassword}, then set a private password: ${loginUrl}` }),
      ]
    : [send({ to: [customer.email], subject: "Investment request received", html: emailTemplate({ title: "Investment request received", intro: "Your investment request has been received. Our team will send investment advice and confirmation within 24 hours.", cta: { label: "Open customer portal", href: `${siteUrl}/portal` } }), text: "Your investment request has been received. Our team will send investment advice and confirmation within 24 hours." })];
  return Promise.all([...customerMessages, notifyAdmins(`Investment request: ${customer.first_name} ${customer.last_name}`, "A customer submitted an investment request.", [["Customer", `${customer.first_name} ${customer.last_name}`], ["Email", customer.email], ["Amount", `₦${Number(investment.amount).toLocaleString()}`], ["Vehicle", investment.vehicle || "ethical"]])]);
}
export async function sendPortalFundingEmails({ customer, request }) { return Promise.all([send({ to: [customer.email], subject: "Funding request received", html: emailTemplate({ title: "Funding request received", intro: `Your funding request has been received for account ${customer.account_number}.` }), text: "Your funding request has been received." }), notifyAdmins(`Funding request: ${customer.first_name} ${customer.last_name}`, "A customer requested funding.", [["Amount", `₦${Number(request.amount).toLocaleString()}`]])]); }
export async function sendPortalLoanEmails({ customer, request }) { return Promise.all([send({ to: [customer.email], subject: "Loan request received", html: emailTemplate({ title: "Loan request received", intro: "Your loan request has been received. NEAT Ethical will respond within 48 hours." }), text: "Your loan request has been received." }), notifyAdmins(`Loan request: ${customer.first_name} ${customer.last_name}`, "A customer submitted a loan request.", [["Amount", `₦${Number(request.amount).toLocaleString()}`], ["Term", `${request.term_months} months`]])]); }
