import { ArrowDownLeft, ArrowUpRight, Banknote, CircleDollarSign, ReceiptText } from "lucide-react";
import { redirect } from "next/navigation";
import { CustomerPortalSection } from "@/components/customer-portal-section";
import { getCustomerSession } from "@/lib/customer-auth";
import { createSupabaseServerClient } from "@/lib/supabase-server";

export const dynamic = "force-dynamic";
export default async function CustomerTransactionsPage() {
  const { customer } = await getCustomerSession(); if (!customer) redirect("/auth/login?redirectTo=/portal/transactions");
  const supabase = createSupabaseServerClient();
  const [{ data: transactions = [] }, { data: funding = [] }, { data: loans = [] }] = await Promise.all([
    supabase.from("transactions").select("id, uuid, kind, direction, amount, status, value_date, created_at, reference, note").eq("customer_id", customer.id).order("value_date", { ascending: false }),
    supabase.from("funding_requests").select("id, uuid, amount, status, created_at").eq("customer_id", customer.id).order("created_at", { ascending: false }),
    supabase.from("loan_requests").select("id, uuid, amount, status, created_at, purpose").eq("customer_id", customer.id).order("created_at", { ascending: false }),
  ]);
  const inTotal = transactions.filter((item) => item.direction === "in").reduce((sum, item) => sum + Number(item.amount || 0), 0); const outTotal = transactions.filter((item) => item.direction === "out").reduce((sum, item) => sum + Number(item.amount || 0), 0);
  const pending = [...funding.map((item) => ({ ...item, kind: "funding request", direction: "in", pending: true })), ...loans.map((item) => ({ ...item, kind: "loan request", direction: "out", pending: true }))];
  const ledger = [...transactions, ...pending].sort((a, b) => new Date(b.value_date || b.created_at) - new Date(a.value_date || a.created_at));
  return <CustomerPortalSection customer={customer} eyebrow="Transactions" title="Money movement" description="A complete record of funds into and out of your NEAT account, including investments, payouts, fees, and loan activity."><section className="grid gap-4 sm:grid-cols-3"><Metric icon={ArrowDownLeft} label="Money in" value={`₦${inTotal.toLocaleString()}`} tone="text-emerald-600" /><Metric icon={ArrowUpRight} label="Money out" value={`₦${outTotal.toLocaleString()}`} tone="text-rose-600" /><Metric icon={Banknote} label="Pending requests" value={pending.length} tone="text-[#075ca8]" /></section><section className="mt-7 overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-100 px-6 py-5"><div><h2 className="text-lg font-black text-slate-950">Transaction history</h2><p className="mt-1 text-sm font-semibold text-slate-500">Cleared transactions and requests awaiting processing.</p></div><ReceiptText className="size-5 text-slate-300" /></div>{ledger.length ? <div className="divide-y divide-slate-100">{ledger.map((item) => { const inbound = item.direction === "in"; return <div key={`${item.pending ? "request" : "transaction"}-${item.id}`} className="flex flex-wrap items-center justify-between gap-4 px-6 py-5"><div className="flex items-center gap-4"><span className={`grid size-11 place-items-center rounded-2xl ${inbound ? "bg-emerald-50 text-emerald-600" : "bg-rose-50 text-rose-600"}`}>{inbound ? <ArrowDownLeft className="size-5" /> : <ArrowUpRight className="size-5" />}</span><div><p className="font-black capitalize text-slate-950">{String(item.kind || "transaction").replace(/_/g, " ")}</p><p className="mt-1 text-sm font-semibold text-slate-500">{item.value_date || new Date(item.created_at).toLocaleDateString("en-NG")} · {item.reference || item.note || "NEAT account activity"}</p></div></div><div className="text-right"><p className={`font-black ${inbound ? "text-emerald-600" : "text-rose-600"}`}>{inbound ? "+" : "−"}₦{Number(item.amount || 0).toLocaleString()}</p><span className="mt-1 inline-block rounded-full bg-slate-100 px-3 py-1 text-xs font-black capitalize text-slate-600">{item.status || "pending"}</span></div></div>; })}</div> : <div className="px-6 py-14 text-center"><ReceiptText className="mx-auto size-10 text-slate-200" /><h3 className="mt-4 text-lg font-black">No transactions yet</h3><p className="mx-auto mt-2 max-w-md text-sm font-semibold leading-6 text-slate-500">When funds are received, invested, paid out, charged as fees, or connected to a loan, they will appear here.</p></div>}</section></CustomerPortalSection>;
}
function Metric({ icon: Icon, label, value, tone }) { return <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><Icon className={`size-5 ${tone}`} /><p className="mt-4 text-2xl font-black text-slate-950">{value}</p><p className="mt-1 text-xs font-bold text-slate-500">{label}</p></div>; }
