import Link from "next/link";
import { ArrowLeft, CalendarDays, CircleDollarSign, FileText, Landmark } from "lucide-react";
import { notFound, redirect } from "next/navigation";
import { CustomerPortalSection } from "@/components/customer-portal-section";
import { getCustomerSession } from "@/lib/customer-auth";
import { createSupabaseServerClient } from "@/lib/supabase-server";

export const dynamic = "force-dynamic";
export default async function InvestmentDetailPage({ params }) {
  const { investment_id: investmentId } = await params; const { customer } = await getCustomerSession(); if (!customer) redirect(`/auth/login?redirectTo=/portal/investments/${investmentId}`);
  const supabase = createSupabaseServerClient(); const { data: investment } = await supabase.from("investments").select("*").eq("customer_id", customer.id).or(`uuid.eq.${investmentId},id.eq.${Number(investmentId) || 0}`).maybeSingle();
  if (!investment) notFound();
  const { data: transactions = [] } = await supabase.from("transactions").select("id, kind, direction, amount, status, value_date, reference, note").eq("investment_id", investment.id).order("value_date", { ascending: false });
  const rows = [["Reference", investment.uuid || investment.id], ["Investment option", investment.vehicle === "funding" ? "Ethical Funding" : "Ethical Investment"], ["Requested amount", `₦${Number(investment.amount || 0).toLocaleString()}`], ["Status", investment.status || "pending"], ["Start date", investment.start_date || "To be confirmed"], ["End date", investment.end_date || "To be confirmed"], ["Payout schedule", investment.payout_schedule || "To be confirmed"], ["Rollover", investment.rollover ? "Yes" : "No"]];
  return <CustomerPortalSection customer={customer} eyebrow="Investment details" title={investment.vehicle === "funding" ? "Ethical Funding" : "Ethical Investment"} description="A complete view of this placement, including its status, terms, and money movement."><Link href="/portal/investments" className="mb-6 inline-flex items-center gap-2 text-sm font-black text-[#075ca8]"><ArrowLeft className="size-4" />Back to investments</Link><div className="grid gap-6 xl:grid-cols-[1.1fr_.9fr]"><section className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><div className="bg-[#075ca8] p-7 text-white"><p className="text-xs font-black uppercase tracking-[.18em] text-blue-100">Current placement</p><p className="mt-4 text-4xl font-black">₦{Number(investment.amount || 0).toLocaleString()}</p><span className="mt-5 inline-block rounded-full bg-white/15 px-3 py-1 text-xs font-black capitalize">{investment.status || "pending"}</span></div><dl className="grid gap-px bg-slate-100 sm:grid-cols-2">{rows.map(([label, value]) => <div key={label} className="bg-white p-5"><dt className="text-xs font-black uppercase tracking-wider text-slate-400">{label}</dt><dd className="mt-2 text-sm font-bold capitalize text-slate-900">{value}</dd></div>)}</dl></section><section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center gap-3"><span className="grid size-11 place-items-center rounded-2xl bg-blue-50 text-[#075ca8]"><CalendarDays className="size-5" /></span><div><p className="font-black text-slate-950">Investment timeline</p><p className="text-sm font-semibold text-slate-500">Status and next steps</p></div></div><div className="mt-6 space-y-5"><Timeline icon={FileText} title="Request submitted" value={investment.submitted_at || investment.created_at} /><Timeline icon={Landmark} title="Team review" value={investment.status === "pending" ? "Awaiting NEAT confirmation" : "Reviewed by NEAT"} /><Timeline icon={CircleDollarSign} title="Funding" value={investment.funded_at || "Pending confirmation"} /></div></section></div><section className="mt-6 rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-lg font-black text-slate-950">Transactions for this investment</h2><div className="mt-4 divide-y divide-slate-100">{transactions.length ? transactions.map((item) => <div key={item.id} className="flex items-center justify-between gap-4 py-4"><div><p className="font-black capitalize">{item.kind?.replace(/_/g, " ")}</p><p className="mt-1 text-sm font-semibold text-slate-500">{item.value_date || "Processing"}</p></div><p className={`font-black ${item.direction === "out" ? "text-rose-600" : "text-emerald-600"}`}>{item.direction === "out" ? "−" : "+"}₦{Number(item.amount || 0).toLocaleString()}</p></div>) : <p className="py-5 text-sm font-semibold text-slate-500">No money movement has been recorded for this investment yet.</p>}</div></section></CustomerPortalSection>;
}
function Timeline({ icon: Icon, title, value }) { const detail = typeof value === "string" && !value.includes("T") ? value : new Date(value).toLocaleDateString("en-NG", { dateStyle: "medium" }); return <div className="flex gap-3"><span className="grid size-8 shrink-0 place-items-center rounded-full bg-slate-100 text-slate-500"><Icon className="size-4" /></span><div><p className="text-sm font-black">{title}</p><p className="mt-1 text-xs font-semibold text-slate-500">{detail}</p></div></div>; }
